#!/bin/bash -x
# File: "/etc/pm/sleep.d/99_cyapa".


# Taken from: http://askubuntu.com/questions/20585/how-to-lock-xscreensaver-on-suspend
# Lock xscreensaver on resume from a suspend.
# getXuser gets the X user belonging to the display in $displaynum.
# If you want the foreground X user, use getXconsole!
getXuser() {
        user=`pinky -fw | awk '{ if ($2 == ":'$displaynum'" || $(NF) == ":'$displaynum'" ) { print $1; exit; } }'`
        if [ x"$user" = x"" ]; then
                startx=`pgrep -n startx`
                if [ x"$startx" != x"" ]; then
                        user=`ps -o user --no-headers $startx`
                fi
        fi
        if [ x"$user" != x"" ]; then
                userhome=`getent passwd $user | cut -d: -f6`
                export XSESSIONRC=$userhome/.xsessionrc
        else
                export XSESSIONRC=""
        fi
}

case "${1}" in
    hibernate)
	/sbin/rmmod cyapa
        ;;
    resume|thaw)
        COUNTER=0
        while [  $COUNTER -lt 10 ]; do
            date >>/tmp/99_cyapa
            /sbin/modprobe cyapa
	    sleep 1
	    dmesg | grep cyapa | tail -1 | grep "\(error\|fail\)" >/dev/null
	    RES=$?
	    if [ ${RES} -ne 1 ] ; then
		/sbin/rmmod cyapa
		sleep 1
	    else
		#done
		COUNTER=11
	    fi
	    
            COUNTER=`expr $COUNTER + 1`
        done
        ;;
esac

exit 0
